import darkBerry from "../../public/nano/dark-berry.svg";
import banana from "../../public/nano/banana.svg";
import blueberry from "../../public/nano/blueberry.svg";
import raspberry from "../../public/nano/raspberry.svg";
import spinach from "../../public/nano/spinach.svg";
import pineapple from "../../public/nano/pineapple.svg";
import mango from "../../public/nano/mango.svg";
import cherry from "../../public/nano/chery.svg";
import peach from "../../public/nano/peach.svg";

export const nanoItems = [
  {
    title: "dark berry",
    image: darkBerry,
    size: "4x nanosmoothies",
    pouch: "100g pouch",
    freshSize: "672g fresh",
    desc1: `A delicious blend of the freeze-dried powders which constitute the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make your custom smoothies, desserts and more, with the natural equivalent of 672 grams of fresh fruit and spinach",
    type1: "powder",
    type2: "sliced",
    hasType1: true,
    hasType2: false,
    category: "mix",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "mango",
    image: mango,
    size: "4x nanosmoothies",
    pouch: "100g pouch",
    freshSize: "672g fresh",
    desc1: `A delicious blend of the freeze-dried powders which constitute the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make your custom smoothies, desserts and more, with the natural equivalent of 672 grams of fresh fruit and spinach",
    type1: " powder",
    type2: "chunks",
    hasType1: false,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "peach",
    image: peach,
    size: "4x nanosmoothies",
    pouch: "100g pouch",
    freshSize: "672g fresh",
    desc1: `A delicious blend of the freeze-dried powders which constitute the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make your custom smoothies, desserts and more, with the natural equivalent of 672 grams of fresh fruit and spinach",
    type1: "powder",
    type2: "sliced",
    hasType1: false,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "cherry",
    image: cherry,
    size: "4x nanosmoothies",
    pouch: "100g pouch",
    freshSize: "672g fresh",
    desc1: `A delicious blend of the freeze-dried powders which constitute the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make your custom smoothies, desserts and more, with the natural equivalent of 672 grams of fresh fruit and spinach",
    type1: "powder",
    type2: "whole",
    hasType1: false,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "banana",
    image: banana,
    size: "387g fresh banana",
    pouch: "100g pouch",
    freshSize: "387g fresh",
    desc1: `Exactly the same pure, natural unmodified freeze-dried banana powder which is blended within the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make healthy desserts, top up your drinks, smoothies and more, with the natural equivalent of 387 grams of fresh banana",
    type1: "powder",
    type2: "sliced",
    hasType1: true,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "blueberries",
    image: blueberry,
    size: "778g fresh blueberries",
    pouch: "100g pouch",
    freshSize: "778g fresh",
    desc1: `Exactly the same pure, natural unmodified freeze-dried blueberry powder which is blended within the infamous <span style="font-weight: 700">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make healthy desserts, top up your drinks, smoothies and more, with the natural equivalent of 778 grams of fresh blueberries",
    type1: "powder",
    type2: "whole",
    hasType1: true,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "raspberry",
    image: raspberry,
    size: "877g fresh raspberries",
    pouch: "100g pouch",
    freshSize: " 877g fresh",
    desc1: `Exactly the same pure, natural unmodified freeze-dried raspberry powder which is blended within the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make healthy desserts, top up your drinks, smoothies and more, with the natural equivalent of 877 grams of fresh raspberries",
    type1: "powder",
    type2: "whole",
    hasType1: true,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
  {
    title: "spinach",
    image: spinach,
    size: "441g fresh spinach",
    pouch: "100g pouch",
    freshSize: "441g fresh",
    desc1: `Exactly the same pure, natural unmodified freeze-dried spinach powder which is blended within the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to increase the nutritional value of any of your meals, drinks and smoothies, with the natural equivalent of 441 grams of fresh spinach ",
    type1: "powder",
    type2: "whole",
    hasType1: true,
    hasType2: false,
    category: "greens",
    link: "nano-greens",
    price: 9,
  },
  {
    title: "pineapple",
    image: pineapple,
    size: "697g fresh pineapple",
    pouch: "100g pouch",
    freshSize: "697g fresh",
    desc1: `Exactly the same pure, natural unmodified freeze-dried pineapple powder which is blended within the infamous <span style="font-weight: 700;">nano</span>smoothie®`,
    desc2:
      "You can use this 100 gram pouch to make healthy desserts, top up your drinks, smoothies and more, with the natural equivalent of 697 grams of fresh pineapple",
    type1: "powder",
    type2: "sliced",
    hasType1: true,
    hasType2: true,
    category: "fruit",
    link: "nano-fruits",
    price: 9,
  },
];
